on: [push]

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'
      - uses: DeLaGuardo/setup-clojure@master
        with:
          cli: '1.11.1.1342'
      - uses: actions/cache@v3
        with:
          path: '~/.m2'
          key: "${{ runner.os }}-maven-${{ hashFiles('deps.edn') }}"
          restore-keys: |
            ${{ runner.os }}-maven-

      - run: clojure -M:cljfmt check
        working-directory: ./importer
      - run: clojure -M:clj-kondo
        working-directory: ./importer

      - run: clojure -M:cljfmt check
        working-directory: ./web
      - run: clojure -M:clj-kondo
        working-directory: ./web
  deploy:
    needs: test
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'
      - uses: DeLaGuardo/setup-clojure@master
        with:
          cli: '1.11.1.1342'
      - uses: actions/cache@v3
        with:
          path: '~/.npm'
          key: "${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}"
          restore-keys: |
            ${{ runner.OS }}-node-
      - uses: actions/cache@v2
        with:
          path: '~/.m2'
          key: "${{ runner.os }}-maven-${{ hashFiles('deps.edn') }}"
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Build artifacts
        run: |
          cd web
          clojure -Stree
          yarn install
          yarn release
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          branch: gh-pages
          folder: web/resources/public
