on: [push]

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '11'
      - uses: DeLaGuardo/setup-clojure@master
        with:
          cli: '1.11.3.1463'
      - uses: actions/cache@v4
        with:
          path: '~/.m2'
          key: "${{ runner.os }}-maven-${{ hashFiles('deps.edn') }}"
          restore-keys: |
            ${{ runner.os }}-maven-

      - run: clojure -M:cljfmt check
        working-directory: ./importer
      - run: clojure -M:clj-kondo
        working-directory: ./importer

      - run: clojure -M:cljfmt check
        working-directory: ./web
      - run: clojure -M:clj-kondo
        working-directory: ./web
  deploy:
    needs: test
    if: github.ref == 'refs/heads/master'
    concurrency:
      group: ${{ github.workflow }}-deploy
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '14'
      - uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '11'
      - uses: DeLaGuardo/setup-clojure@master
        with:
          cli: '1.11.3.1463'
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT
      - uses: actions/cache@v4
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - uses: actions/cache@v4
        with:
          path: '~/.m2'
          key: "${{ runner.os }}-maven-${{ hashFiles('deps.edn') }}"
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Build artifacts
        run: |
          cd web
          clojure -Stree
          yarn install
          yarn release
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: web/resources/public
