on:
  schedule:
    - cron: '0 0 * * mon'
  workflow_dispatch: ~

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  create-project-data:
    runs-on: ubuntu-latest
    env:
      JAVA_OPTS: '-Dclojure.main.report=stderr'
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-java@v5
        with:
          distribution: 'adopt'
          java-version: '25'
      - uses: DeLaGuardo/setup-clojure@master
        with:
          cli: '1.12.4.1618'
      - uses: actions/cache@v5
        with:
          path: '~/.m2'
          key: "${{ runner.os }}-maven-${{ hashFiles('deps.edn') }}"
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Get month
        id: get-month
        run: |
          echo "day=$(date +%Y-%m)" >> $GITHUB_OUTPUT
        shell: bash
      - uses: actions/cache/restore@v5
        id: url-cache-restore
        with:
          path: './importer/resources/.cache/url'
          key: "url-${{ steps.get-month.outputs.day }}"
      - run: |
          cd importer
          clojure -X app.core/create-projects-data
      - name: Upload project data
        uses: actions/upload-artifact@v7
        with:
          name: project-data
          path: importer/target
          if-no-files-found: error
          retention-days: 7
      - uses: actions/cache/save@v5
        if: always() && steps.url-cache-restore.outputs.cache-hit != 'true'
        with:
          path: './importer/resources/.cache/url'
          key: ${{ steps.url-cache-restore.outputs.cache-primary-key }}
  create-data-from-project-data:
    needs: create-project-data
    runs-on: ubuntu-latest
    env:
      JAVA_OPTS: '-Dclojure.main.report=stderr'
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-java@v5
        with:
          distribution: 'adopt'
          java-version: '25'
      - uses: DeLaGuardo/setup-clojure@master
        with:
          cli: '1.12.4.1618'
      - uses: actions/cache@v5
        with:
          path: '~/.m2'
          key: "${{ runner.os }}-maven-${{ hashFiles('deps.edn') }}"
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Download data
        uses: actions/download-artifact@v8
        with:
          name: project-data
          path: importer/target
      - name: Get month
        id: get-month
        run: |
          echo "day=$(date +%Y-%m)" >> $GITHUB_OUTPUT
        shell: bash
      - uses: actions/cache@v5
        with:
          path: './importer/resources/.cache/url'
          key: "url-${{ steps.get-month.outputs.day }}"
      - run: |
          cd importer/
          clojure -X app.core/create-data-from-projects-data
      - name: Push changes
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add .
          git commit -m "Update game list" || true
          git push
