on:
  schedule:
    - cron: '0 0 * * mon'
  workflow_dispatch: ~

jobs:
  get-projects:
    runs-on: ubuntu-20.04
    outputs:
      projects: ${{ steps.get-projects.outputs.projects }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'
      - uses: DeLaGuardo/setup-clojure@master
        with:
          cli: '1.11.1.1342'
      - uses: actions/cache@v3
        with:
          path: '~/.m2'
          key: "${{ runner.os }}-maven-${{ hashFiles('deps.edn') }}"
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Get projects
        id: get-projects
        run: |
          cd ./importer/
          echo "projects=$(clojure -X app.core/list-projects)" >> "$GITHUB_OUTPUT"
  update:
    needs: get-projects
    runs-on: ubuntu-20.04
    strategy:
      max-parallel: 1
      matrix:
        project: ${{ fromJson(needs.get-projects.outputs.projects) }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'
      - uses: DeLaGuardo/setup-clojure@master
        with:
          cli: '1.11.1.1342'
      - uses: actions/cache@v3
        with:
          path: '~/.m2'
          key: "${{ runner.os }}-maven-${{ hashFiles('deps.edn') }}"
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Get month
        id: get-month
        run: |
          echo "day=$(date +%Y-%m)" >> $GITHUB_OUTPUT
        shell: bash
      - uses: actions/cache@v3
        with:
          path: './importer/resources/.cache/url'
          key: "url-${{ steps.get-month.outputs.day }}"
      - name:
        run: |
          cd ./importer/
          clojure -X app.core/create-data :project '"${{ matrix.project }}"'
      - name: Upload data
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.project }}
          path: web/src/app/${{ matrix.project }}_data.cljc
          if-no-files-found: error
          retention-days: 7
  create-pr:
    needs: update
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Download data
        uses: actions/download-artifact@v4
        with:
          path: web/src/app
          merge-multiple: true
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: Update game list
          title: Update game list
          branch: create-pull-request/update-game-list
          delete-branch: true
