on:
  schedule:
    - cron: '0 0 * * mon'
  workflow_dispatch: ~

jobs:
  update:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
      - uses: DeLaGuardo/setup-clojure@master
        with:
          cli: '1.10.3.855'
      - uses: actions/cache@v2
        with:
          path: '~/.m2'
          key: "${{ runner.os }}-maven-${{ hashFiles('deps.edn') }}"
          restore-keys: |
            ${{ runner.os }}-maven-
      - name:
        run: |
          cd ./importer/
          clojure -M -m app.core > ../web/src/app/data.cljs
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: Update game list
          title: Update game list
          branch: create-pull-request/update-game-list
          delete-branch: true
