on:
  schedule:
    - cron: '0 0 * * mon'
  workflow_dispatch: ~

jobs:
  update:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'
      - uses: DeLaGuardo/setup-clojure@master
        with:
          cli: '1.11.1.1273'
      - uses: actions/cache@v3
        with:
          path: '~/.m2'
          key: "${{ runner.os }}-maven-${{ hashFiles('deps.edn') }}"
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Get month
        id: get-month
        run: |
          echo "::set-output name=day::$(date +%Y-%m)"
        shell: bash
      - uses: actions/cache@v2
        with:
          path: './importer/resources/.cache/url'
          key: "url-${{ steps.get-month.outputs.day }}"
      - name:
        run: |
          cd ./importer/
          clojure -X app.core/create-data
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: Update game list
          title: Update game list
          branch: create-pull-request/update-game-list
          delete-branch: true
